In [1]:
from vector_class import Vector
from random import randint
from itertools import cycle
from math import sqrt
import numpy as np

## Exercise 7.1

In [2]:
def find_axis(v1 : Vector, v2 : Vector) -> Vector:
    '''
    Returns the unit vector v3, where v3 is perpendicular to the vectors v1 and v2.
    
    Args:
        v1: instance of Vector class
        v2: instance of vector class
        
    Raises:
        ValueError when vectors are parallel or at least one of them is zero
    '''
    vector_zero = Vector(0, 0, 0)
    cross_product = v1.cross(v2)
    if cross_product == vector_zero or v1 == vector_zero or v2 == vector_zero:
        raise ValueError ('Vectors are parallel or at least one of them is zero.')
    cross_length = cross_product.length()
    cross_product.x /= cross_length
    cross_product.y /= cross_length
    cross_product.z /= cross_length
    return cross_product

In [3]:
v1 = Vector(1, 1, 1)
v2 = Vector(1, 0, 1)
v3 = Vector(0, 0, 0)

In [4]:
find_axis(v1, v2)

Vector(0.7071067811865475, 0.0, -0.7071067811865475)

In [5]:
find_axis(v1, v3)

ValueError: Vectors are parallel or at least one of them is zero.

## Exercise 7.2

In [6]:
# Iterator based on callable object
class mod2:
    
    def __init__(self):
        self.n = 1
        
    def __call__(self):
        self.n += 1
        self.n %= 2
        return self.n

In [7]:
x = mod2()
iter_1 = iter(x, 2)

In [8]:
for i in range(7):
    print(next(iter_1), end = ', ')
print(next(iter_1))

0, 1, 0, 1, 0, 1, 0, 1


In [9]:
# Iterator based on callable object
iter_2 = iter((lambda: randint(0, 1)), 2)

In [10]:
for i in range(7):
    print(next(iter_2), end = ', ')
print(next(iter_2))

1, 0, 0, 0, 1, 0, 0, 1


In [11]:
# Using itertools cycle
iter_3 = cycle([0, 1, 0, -1])

In [12]:
for i in range(7):
    print(next(iter_3), end = ', ')
print(next(iter_3))

0, 1, 0, -1, 0, 1, 0, -1


## Exercise 7.3

In [13]:
arr = np.linspace(0, 1, num=11, dtype = np.dtype('float'))
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
print(arr.shape)
print(arr.dtype)

(11,)
float64


In [15]:
arr_ = np.zeros((5, 6), dtype = np.dtype('int8'))
arr_

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [16]:
print(arr_.shape)
print(arr_.dtype)

(5, 6)
int8


In [17]:
arr__ = np.array([np.power(1J, i) for i in range(1, 10)], dtype = np.dtype('complex'))
arr__

array([ 0.+1.j, -1.+0.j, -0.-1.j,  1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j,
        1.+0.j,  0.+1.j])

In [18]:
print(arr__.shape)
print(arr__.dtype)

(9,)
complex128
