In [1]:
import numpy as np

## Exercise 8.1

In [2]:
arr = np.linspace(0, 1, num=11, dtype = np.dtype('float'))
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [3]:
print(arr.shape)
print(arr.dtype)

(11,)
float64


In [4]:
arr_ = np.zeros((5, 6), dtype = np.dtype('int8'))
arr_

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [5]:
print(arr_.shape)
print(arr_.dtype)

(5, 6)
int8


In [6]:
arr__ = np.array([np.power(1J, i) for i in range(1, 10)], dtype = np.dtype('complex'))
arr__

array([ 0.+1.j, -1.+0.j, -0.-1.j,  1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j,
        1.+0.j,  0.+1.j])

In [7]:
print(arr__.shape)
print(arr__.dtype)

(9,)
complex128


## Exercise 8.2

In [8]:
v1 = np.array(range(1, 99, 3), dtype=np.dtype('uint8'))
v1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97],
      dtype=uint8)

In [9]:
print(v1.ndim)

1


In [10]:
# slice give us view, so we use copy to create new array
v2 = v1[1::2].copy()
v2

array([ 4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94],
      dtype=uint8)

In [11]:
v3 = v1[::-1].copy()
v3

array([97, 94, 91, 88, 85, 82, 79, 76, 73, 70, 67, 64, 61, 58, 55, 52, 49,
       46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10,  7,  4,  1],
      dtype=uint8)

## Exercise 8.3

In [12]:
# set seed for reproducibility
np.random.seed(42)
m1 = np.random.rand(4, 5)
m1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [13]:
print(m1.shape)

(4, 5)


In [14]:
# rows reverse order
m2 = m1[:, ::-1].copy()
m2

array([[0.15601864, 0.59865848, 0.73199394, 0.95071431, 0.37454012],
       [0.70807258, 0.60111501, 0.86617615, 0.05808361, 0.15599452],
       [0.18182497, 0.21233911, 0.83244264, 0.96990985, 0.02058449],
       [0.29122914, 0.43194502, 0.52475643, 0.30424224, 0.18340451]])

In [15]:
# columns reverse order
m3 = m1[::-1, :].copy()
m3

array([[0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864]])

In [16]:
m1[1:-1, 1:-1]

array([[0.05808361, 0.86617615, 0.60111501],
       [0.96990985, 0.83244264, 0.21233911]])